### ISSUE TITLE
Move Static Config values into a Database Table.

### ISSUE THREAD

**Issue by dazinator** [ReachContact/GCTactical-Issues#2]
The app currently has some static config values (hardcoded) such as endpoint url's etc.
1. Create a table in the database to store these config values.
2. Ensure table is populated with default config values.
3. Change config class to initialise values form the database once, and cache them in memory.

The new Config class will only provide read only access to the config values (pulled from the database into a cache) at this point in time.

The cache will not be invalidated meaning that new config will only take effect when the applications is restarted.

**Comment by dazinator** [comment]
@ipunch @bobbyfischer -  does this look ok with you both - before I start?

**Comment by bobbyfischer** [comment]
Hi Darrell,

Yes looks good to me

Thanks

**Comment by dazinator** [comment]
Done in revision 278
