### ISSUE TITLE
Revise MVC pattern

### ISSUE THREAD

**Issue by dazinator** [ReachContact/GCTactical-Issues#9]
Rather than each view having properties / methods to set each control's value, e.g:

``` csharp

 public interface ISyncView : IView
  {

        void UpdateDownloadProgressControls(int currentCount, int totalCount, int callfileId);

        void UpdateOutletDownloadProgressControls(int currentCount, int totalCount, int outletId);

        void UpdateCampaignDownloadProgressControls(int currentCount, int totalCount, int campaignId);


.. shortened for brevity

}
```

It might be better to create a `ViewModel` to hold the view's state:

``` csharp
public class SyncViewModel
{  
        int CallFileId { get; set; }

        int DownloadProgressCurrent { get; set; }
        int DownloadProgressTotal { get; set; }

        int OutletDownloadProgressCurrent { get; set; }
        int OutletDownloadProgressTotal { get; set; }

        int CampaignDownloadProgressCurrent { get; set; }
        int CampaignDownloadProgressTotal { get; set; }
}
```

*\* The view model would need to also implement `INotifyPropertyChanged` to support databinding. **

And then for there to be a generic `IView<TModel>` base class, which has stuff like:

```
void BindModel(T model); // Called when the UI needs to wire its controls up to model state.
T Model { get; } // Provides access to the current model the view is bound to.
```

Each view would have a single property called `Model` that provides access to the model for that view. The view can wire its's controls up to that model's properties as it sees fit. It can listen for property change notifications on that model's properties, and update / set UI control values, and likewise it can handle control values changing, and can set update the model's property values (a poor mans databinding)

This will mean that the interfaces for each view will become much less granular as they will have methods for processing the Model as a whole and not individual control values, i.e the code in the controllers, rather than setting each views property as so:

``` csharp
View.UpdateUploadProgressControls(10,100,123);
View.UpdateOutletDownloadProgressControls(10,100,123);
View.UpdateCampaignDownloadProgressControls(10,100,123);
```

Could become like this:

``` csharp

View.BindModel(new SyncModel());

// Upon changing the model's property values,property change notifications are raised by
// the model, which the View subscribed handlers to in the above `BindModel` method. 
// The view updates the relevent control's value for the relevant property change. 
View.Model.DownloadProgressCurrent = 10;
View.Model.DownloadProgressTotal = 100;
View.Model.CallfileId= 123;
```

Note that the View interface is only providing access to the `Model` , and not each and every control value - as the actual state for each control's value is held on the model.

For screens that have a lot of state and properties, this should cut down on the amount of interface code that has to be written / implemented, but it does require that we create "View Models" to represent the state for each of our views, and also change the code to implement some form of databinding with those view models..

**Comment by dazinator** [comment]
@ipunch @bobbyfischer - this was just an idea at present - have a read and see what you think

**Comment by ipunch** [comment]
Sounds like a great idea to me.  Seems the proper way to do things, I missed out the databinding stuff so will be good to have this implemented

**Comment by dazinator** [comment]
One important thing about raising property change notifications is not to raise them unless the properties value is actual different! Otherwise you'd get this loop:
1. Property is changed on view model (raises property changed event)
2. View handles property changed event and updates a control's value, which fires a control's value changed event
3. View handles the controls value changed event, and updates the model's property value (with the same value)
4. Repeat this loop from 1!

This is why it's a poor man's databinding because we would need to handle this kind of implementation detail ourselves because we don't have a proper data binding mechanism library / extension for android.

The quick workaround for this problem is for the view model to only raise property changed notifications when the value is different - e.g:

``` csharp
 public Color Color
        {
            set
            {
                if (color != value)
                {
                    color = value;
                    OnPropertyChanged("Color");                   
                }
            }
            get
            {
                return color;
            }
        }
```

This doesn't stop the roundtrip of a property change bubbling up the UI and then back down to the view model a second time, but atleast on the second time the journey ends and there won't be an infinite loop as described.

**Comment by dazinator** [comment]
Have now adopted MVVMCross which offers a nicer framework to use moving forwards. Nothing with the existing MVC structure needs to change (unless we want to convert them for any reason to MVVM) but new screens can be done using MVVMCross.

**Comment by dazinator** [comment]
Closing this now, as MvvmCross has been adopted, and the Login screen serves as the primary example of the new architectural pattern.
